# Generated by Django 4.1.2 on 2022-10-30 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('instructor_name', models.CharField(blank=True, max_length=50)),
                ('instructor_email', models.CharField(blank=True, max_length=50)),
                ('course_number', models.IntegerField(primary_key=True, serialize=False)),
                ('semester_code', models.IntegerField(blank=True, null=True)),
                ('course_section', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=40)),
                ('catalog_number', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('units', models.CharField(blank=True, max_length=100)),
                ('component', models.CharField(blank=True, max_length=100)),
                ('class_capacity', models.IntegerField(blank=True, null=True)),
                ('wait_list', models.IntegerField(blank=True, null=True)),
                ('wait_cap', models.IntegerField(blank=True, null=True)),
                ('enrollment_total', models.IntegerField(blank=True, null=True)),
                ('enrollment_available', models.IntegerField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=50)),
                ('meetings_days', models.CharField(blank=True, max_length=100)),
                ('meetings_start_time', models.CharField(blank=True, max_length=500)),
                ('meetings_end_time', models.CharField(blank=True, max_length=500)),
                ('meetings_facility_description', models.CharField(blank=True, max_length=500)),
                ('secondary_meetings_days', models.CharField(blank=True, max_length=100)),
                ('secondary_meetings_start_time', models.CharField(blank=True, max_length=500)),
                ('secondary_meetings_end_time', models.CharField(blank=True, max_length=500)),
                ('secondary_meetings_facility_description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='list_classes.course')),
            ],
        ),
    ]
