# Generated by Django 4.1.2 on 2022-11-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('instructor_name', models.CharField(blank=True, max_length=500)),
                ('instructor_email', models.CharField(blank=True, max_length=500)),
                ('course_number', models.IntegerField(primary_key=True, serialize=False)),
                ('semester_code', models.IntegerField(blank=True, null=True)),
                ('course_section', models.CharField(blank=True, max_length=500)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('catalog_number', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('units', models.CharField(blank=True, max_length=500)),
                ('component', models.CharField(blank=True, max_length=500)),
                ('class_capacity', models.IntegerField(blank=True, null=True)),
                ('wait_list', models.IntegerField(blank=True, null=True)),
                ('wait_cap', models.IntegerField(blank=True, null=True)),
                ('enrollment_total', models.IntegerField(blank=True, null=True)),
                ('enrollment_available', models.IntegerField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=500)),
                ('meetings_days', models.CharField(blank=True, max_length=500)),
                ('meetings_start_time', models.CharField(blank=True, max_length=500)),
                ('meetings_end_time', models.CharField(blank=True, max_length=500)),
                ('meetings_facility_description', models.CharField(blank=True, max_length=500)),
                ('secondary_meetings_days', models.CharField(blank=True, max_length=500)),
                ('secondary_meetings_start_time', models.CharField(blank=True, max_length=500)),
                ('secondary_meetings_end_time', models.CharField(blank=True, max_length=500)),
                ('secondary_meetings_facility_description', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
