# Generated by Django 4.1.1 on 2022-10-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='meetings_days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='meetings_end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='meetings_facility_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='meetings_start_time',
        ),
    ]
