# Generated by Django 4.1.2 on 2022-10-31 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_classes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
