# Generated by Django 4.1.2 on 2022-10-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_classes', '0002_remove_course_meetings_days_and_more'),
        ('list_classes', '0004_alter_course_catalog_number_and_more'),
    ]

    operations = [
    ]
