# Generated by Django 4.1.2 on 2022-10-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_classes', '0005_merge_20221017_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meetings_days',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='component',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
