# Generated by Django 4.1.2 on 2022-10-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_classes', '0006_course_meetings_days_alter_course_component_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='meetings_days',
            new_name='meetings',
        ),
    ]
