# Generated by Django 4.1.2 on 2022-10-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_classes', '0007_rename_meetings_days_course_meetings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='meetings',
        ),
    ]
