# Generated by Django 4.1.2 on 2022-10-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_classes', '0009_course_meetings_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='meetings_days',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
