# Generated by Django 4.1.2 on 2022-10-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_classes', '0010_alter_course_meetings_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meetings_end_time',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='meetings_facility_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='meetings_start_time',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='meetings_days',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
