# Generated by Django 4.1.2 on 2022-10-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_classes', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Course',
            new_name='course',
        ),
    ]
