# Generated by Django 4.1.2 on 2022-10-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_classes', '0013_rename_course_comment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='secondary_meetings_days',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='secondary_meetings_end_time',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='secondary_meetings_facility_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='secondary_meetings_start_time',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
