# Generated by Django 4.1.2 on 2022-10-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_classes', '0014_course_secondary_meetings_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='component',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='meetings_days',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='secondary_meetings_days',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
