# Generated by Django 4.1.2 on 2022-10-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_classes', '0015_alter_course_component_alter_course_meetings_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_section',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='catalog_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
